### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by Bykiev** [winarg/ngx-cron-editor#2]
Hi, is localization supported?

**Comment by winarg** [comment]
Hi. Yes it is supported using the i18n tags. If you find any issue, please do not hesitate to open it here!

**Comment by Bykiev** [comment]
Thank you, can you please provide an example as I'm not familiar with i18n tags

**Comment by winarg** [comment]
By using the following command
`ng extract-i18n --output-path locale`
a file is produced in the locale folder which contains the values for each translation.
Then, you can change the "source" value of each "trans-unit".
Take a look [here](https://angular.io/guide/i18n-overview) for the official documentation.
