### ISSUE TITLE
For cronFlavor 'quartz' on select Monthly tab - Day dropdown disabled or not working. 

### ISSUE THREAD

**Issue by Maroti-Kharate** [winarg/ngx-cron-editor#4]
Hi,

Thanks for the awesome cron-editor example. 
Actually, I'm facing issue when cronFlavor  =  'quartz' and select monthly tab, then Day dropdown options get disabled/not works.
Can you please tell us about the purpose for the same? or if it is issue then, how we can fix that? 
 
Please find attachment for more details.
![cron-issue](https://user-images.githubusercontent.com/59495085/204442453-be6ae097-51dd-4f4b-b9f3-a0d8c6c69950.JPG)

Thank you,
Maroti Kharate

**Comment by winarg** [comment]
Hi! Sorry for the late reply!
I will fix it ASAP!

**Comment by winarg** [comment]
Latest version fixes this issue

**Comment by Maroti-Kharate** [comment]
Thanks a lot for your efforts.
Actually we are using Angular 13, tried to update "ngx-cron-editor" version, but it shows below error.
As I understand, latest issue fix need Angler 15, but It will difficult for us to update Angular version as we are closer to production release.
Is It possible to apply same fix in previous A13 version.

![error](https://user-images.githubusercontent.com/59495085/210303154-be369c8a-133a-4f8e-bfae-8d6e25836b74.JPG)

**Comment by winarg** [comment]
I've uploaded version 0.10.1 which (should) allow you to use the component with Angular 13
